### ISSUE TITLE
ability to crop raw data to only include non-zero timepoints before writing out bids data.

### ISSUE THREAD

**Issue by sjapee** [nih-megcore/nih_to_mne#33]
Would it be possible to add the option to exclude data from raw that is all zeros (this happens when recording is longer than the task) and would be useful for self-paced task recordings.  something like the following to remove trailing zeros:
raw.crop(0,raw.times[events[-1,0]]+3)
before calling: 
write_raw_bids(raw, bids_path, overwrite=True)
The above would rely on having events array available.  But perhaps there's another way?

**Comment by jstout211** [comment]
Currently checking with the group if there is a CTF option for this --
Otherwise, we have some code in the eyetracking that will identify when the channels have zeroed out and crop after a certain number of consecutive zeros.  This still leaves us with a .fif file, but you probably want the data in CTF format.  We might be able to use pyctf to cast this back into a CTF dataset.

**Comment by jstout211** [comment]
![image](https://user-images.githubusercontent.com/2371720/225393964-fb2b2b72-d8bf-486b-9264-b917e1ac47c2.png)

**Comment by hyperbolicTom** [comment]
There is a fif2ctf utility in pyctf, but it has only been used with OPM
datasets.
It is easy to modify, and it writes CTF format (bare minimum of files,
.meg4 and .res4)

**Comment by LinaTeichmann1** [comment]
If there is a good solution for this, I'd be interested to make my BIDS datasets smaller! :) Thanks all!

**Comment by jstout211** [comment]
Some progress towards this 05aae3a  -- just need to integrate into the bids component

**Comment by jstout211** [comment]
This is currently implemented with a cmdline argument flag.
